### ISSUE TITLE
"...aapt.exe'' finished with non-zero exit value -1073741819

### ISSUE THREAD

**Issue by liboLiao** [ainsophical/DROID_PYTHON#7]
I use androidStudio 2.2.3 and download apk 2.7, when I build this project,an error occurred. as follows:
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'E:\Soft_Program_Files\sdk\build-tools\21.0.1\aapt.exe'' finished with non-zero exit value -1073741819

**Comment by michaelrinderle** [comment]
i developed this project off a linux based box. try the following SO link for help.

http://stackoverflow.com/questions/29249986/finished-with-non-zero-exit-value
